### ISSUE TITLE
Currently possible to certify a finalised public draw

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-backend#114]
at least, the backend replies with a paypal url

**Comment by mariocj89** [comment]
What should be the time limit for certifying a draw?

**Comment by palvarez89** [comment]
I'd say an hour. Maybe something like 50 minutes in reality to not be super strict.

Another option is to do a combination:
- can't certify finished draw
- can only certify one hour (or even a day) after creation

**Comment by mariocj89** [comment]
Sadly this will be quite hard to implement in the backend for multiple reasons:
- We will need to retrieve the draw, which will require knowing the draw type, something that we do not have today.
- In the backend we do not care about the results generated by a draw. This will be a significant change in our logic.

Given that this is needed as well in the frontend, I think the best cost/effort is to just leave it in the frontend and if we see this being abused we can invest in fixing it in the backend as well.
