### ISSUE TITLE
Title and description should be optional

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-backend#12]
Seems that somewhere in the API these fields are rejected (at least in RandomNumberDraw) when they are empty strings.

**Comment by mariocj89** [comment]
They are optional, you can pass null. Are you saying `''` should be valid?

If so we just need to change blank=True at serializers. But is probably more correct to set null if not set.

**Comment by mariocj89** [comment]
Agreed it is ok not allowing blanks
