### ISSUE TITLE
Warning when using celery for emails

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-backend#127]
```
echaloasuerte_log.txt:[20211027 23:37:31.843] WARNING kombu.connection:connection._info | No hostname was supplied. Reverting to default 'localhost'
```

This should be taking the CELERY_BROKER_URL, but seems to fail.

**Comment by mariocj89** [comment]
I'm considering writing my own celery writer and consumer and just sending emails from the consumer.

We could pass the parameters through rabitmq easily (language, target email and Name to gift).
