### ISSUE TITLE
psycopg2 reanamed

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-backend#38]
/var/www/echaloasuerte-3/venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning:
    The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing
    from binary please use "pip install psycopg2-binary" instead. For details see:
    <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

**Comment by palvarez89** [comment]
heh, in those docs i could see: `Note The -binary package is meant for beginners...`. Let's try to use the non-binary one. It can be specified in the requirements.txt file.

**Comment by mariocj89** [comment]
From the docs: 
> The choices for the users are then two:
> 
> - if the program works fine with the Wheel packages, and the convenience of the binary distribution is preferred, it is possible to specify the dependency on the binary package using the psycopg2-binary instead of the psycopg2 PyPI package. No change to the program code is needed;
> - if there are concerns about the unreliability of the Wheels package, it is adviced to force installation from source. This requires the presence of build tools and runtime libraries on the client, but again it requires no change to the code.

I am going to move it to -binary we we dont need a system dendency for it. If we experience any issue we can move.
