### ISSUE TITLE
Raffle shouldn't require participants to toss

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-backend#54]
## Scenario
A user is setting a facebook raffle. The raffle should be scheduled and later on, participants would be added by hitting the [add participant endpoint](https://github.com/etcaterva/eas-backend/blob/153f56758478a030c1d34dfcdc38f63fd7c24928/swagger.yaml#L65). 

However, scheduling a draw is effectively a `toss`, which now errors if there are no participants.

**Comment by mariocj89** [comment]
What should happen if on the day of the scheduled toss there are fewer participants than prizes?

**Comment by dnaranjo89** [comment]
Hmm.. They could be randomly assign them until any of the groups is
exhausted. Maintaining the prizes order as probably they are ordered by
importance.
We can clarify what happened in the UI and it's up to the organise it to do
what they consider is right.

I think that trying to cover that scenario with settings when creating the
draw could be too much overheat in the UI...

**Comment by mariocj89** [comment]
> I think that trying to cover that scenario with settings when creating the
draw could be too much overheat in the UI...

Agree.

> We can clarify what happened in the UI and it's up to the organise it to do
what they consider is right.

OK, sounds a good idea, what about when there are 0 participants?

**Comment by dnaranjo89** [comment]
This could be handled in the frontend with a message as well? ¯\_(ツ)_/¯

**Comment by mariocj89** [comment]
It cannot as we need to generate the result at that time isn’t it?

Something we can do is just skip generating the result if there are no
participants. How does that sound?

**Comment by dnaranjo89** [comment]
Sounds good to me!
