### ISSUE TITLE
Log at different levels with multiple rotations for easier troubleshooting

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/eas-backend#56]
See how EAS2 was configured [here](https://github.com/etcaterva/echaloasuerte/blob/master/echaloasuerte/settings/prod.py#L28). Follow a similar model where we can see different log levels on different files that rotate at a different pace. This will allow us to quickly log in and see production issues with debug logs, whilst keeping a long trace of errors.

**Comment by palvarez89** [comment]
see https://github.com/etcaterva/eas-backend/pull/58

**Comment by mariocj89** [comment]
Done in #58
