### ISSUE TITLE
Typo on swagger spec

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-backend#92]
There is a typo in the [language parameter](https://github.com/etcaterva/eas-backend/blob/0e9589a69e48709038baa13087a51a90860a4920/swagger.yaml#L903)

**Comment by mariocj89** [comment]
Fixed via https://github.com/etcaterva/eas-backend/commit/8610b4fd57b586bfbad556f3d21d9f15de51a64c
